---
reverse_proxy_marathon_id: /infrastructure/reverse-proxy
# Attach the reverse proxy application to a particular host. The hostname should be the name known by Marathon / Mesos
reverse_proxy_marathon_host: "{{ ansible_fqdn }}"
reverse_proxy_marathon_constraints: [["hostname", "CLUSTER", "{{ reverse_proxy_marathon_host | trim }}"]]

reverse_proxy_docker_image: 'hbpmip/caddy:{{ caddy_version | default(latest) }}'
reverse_proxy_https_port: 443
reverse_proxy_http_port: 80
reverse_proxy_docker_parameters: []

# Provide an email address for the automatic creation of SSL certificates
reverse_proxy_ssl_mode: ''
#reverse_proxy_ssl_mode: self_signed
reverse_proxy_persist_dir: /srv/docker/reverse-proxy/

reverse_proxy_default_auth_login: admin
#reverse_proxy_public_hostname: demo
#reverse_proxy_default_auth_password: test

# mesosui is authenticated
reverse_proxy_mesosui_backend: "{%- if mesos_leader_hostname is defined and mesos_leader_port is defined -%}
http://{{ mesos_leader_hostname }}:{{ mesos_leader_port }}
{%- else -%}
/dev/null
{%- endif -%}"
reverse_proxy_mesosui_auth_login: "{{ reverse_proxy_default_auth_login }}"
reverse_proxy_mesosui_auth_password: "{{ reverse_proxy_default_auth_password }}"

# airflow is authenticated
reverse_proxy_airflow_backend: "{{ airflow_web_base_url | default('/dev/null') }}"
reverse_proxy_airflow_auth_login: "{{ reverse_proxy_default_auth_login }}"
reverse_proxy_airflow_auth_password: "{{ reverse_proxy_default_auth_password }}"

# marathon is authenticated
reverse_proxy_marathon_backend: "{%- if marathon_hostname is defined and marathon_port is defined -%}
http://{{ marathon_hostname }}:{{ marathon_port }}
{%- else -%}
/dev/null
{%- endif -%}"
reverse_proxy_marathon_auth_login: "{{ reverse_proxy_default_auth_login }}"
reverse_proxy_marathon_auth_password: "{{ reverse_proxy_default_auth_password }}"

# woken has an authentication integrated
reverse_proxy_woken_backend: "{%- if woken_host is defined and woken_http_port is defined -%}
http://{{ woken_host }}:{{ woken_http_port }}
{%- else -%}
/dev/null
{%- endif -%}"

portal_frontend_port: 80

# portal_frontend has an authentication integrated
reverse_proxy_portal_frontend_backend: "http://{{ portal_frontend_marathon_host }}:{{ portal_frontend_port | default(80) }}"
#
# portal_backend has an authentication integrated
reverse_proxy_portal_backend_backend: "{%- if portal_backend_marathon_host is defined and portal_backend_port is defined -%}
http://{{ portal_backend_marathon_host }}:{{ portal_backend_port }}
{%- else -%}
/dev/null
{%- endif -%}"
