- name: "set facts for firewall (internal services) port+host"
  set_fact:
    firewall_rules: "{{ firewall_rules|default([]) + [ 'iptables -A INPUT -p tcp --dport ' + item[1]|string + ' -s ' + item[0]|string + ' -j ACCEPT', 'iptables -A INPUT -p tcp --dport ' + item[1]|string + ' -i docker0 -j ACCEPT', 'iptables -A INPUT -p udp --dport ' + item[1]|string + ' -s ' + item[0]|string + ' -j ACCEPT', 'iptables -A INPUT -p udp --dport ' + item[1]|string + ' -i docker0 -j ACCEPT' ] }}"
  with_cartesian:
    - "{{ ips }}"
    - "{{ ports }}"

- name: "set facts for firewall (swarm clustering) port"
  set_fact:
    firewall_rules: "{{ firewall_rules|default([]) + [ 'iptables -A INPUT -p tcp --dport ' + item|string + ' -j ACCEPT', 'iptables -A INPUT -p udp --dport ' + item|string + ' -j ACCEPT' ] }}"
  with_items:
    - "{{ swarm_ports }}"
  when: swarm_firewall_enabled | bool

#- name: "debug"
#  debug:
#    msg: "{{ firewall_rules }}"
