---

zookeeper_port: 2181
ssh_port: 22

mesos_zk_port: "{{ zookeeper_port }}"
mesos_zk_hosts: "{% for host in groups[zookeeper_server_group] %}{{ hostvars[host]['fqdn'] | default(hostvars[host]['ansible_fqdn']) }}:{{ mesos_zk_port }}{% if not loop.last %},{% endif %}{% endfor %}"
mesos_leader_port: 5050
mesos_follower_port: 5051

marathon_port: 5080

# TODO: use role=control ?
zookeeper_server_group: 'zookeeper'
mesos_leader_server_group: "mesos-leader"
mesos_mixed_server_group: "mesos-mixed"

mesos_leader_hostname_default: "
  {%- set mesos_leaders = groups[mesos_leader_server_group] + groups[mesos_mixed_server_group] -%}
  {{- hostvars[mesos_leaders[0]]['fqdn'] | default(hostvars[mesos_leaders[0]]['ansible_fqdn']) -}}
"
mesos_leader_hostname: "{{ mesos_leader_hostname_override | default(mesos_leader_hostname_default|trim) }}"
marathon_hostname: "{{ marathon_hostname_override | default(mesos_leader_hostname) }}"

internal_mesos_url: "http://{{ mesos_leader_hostname }}:{{ mesos_leader_port }}"
internal_marathon_url: "http://{{ marathon_hostname }}:{{ marathon_port }}"

metrics_prometheus_http_port: 31080

# ports 80 and 443 are set here for every machine
infrastructure_ports_public: "
  {%- set ports = [] -%}
  {%- set ports = ports + ['80'] -%}
  {%- set ports = ports + ['443'] -%}
  {%- if ssh_port is defined and ssh_port -%}
    {%- set ports = ports + [ssh_port] -%}
  {%- endif -%}
  {{ ports }}
"
