---

zookeeper_port: 2181
ssh_port: 22

mesos_zk_port: "{{ zookeeper_port }}"
mesos_zk_hosts: "{% for host in groups[zookeeper_server_group] %}{{ hostvars[host]['fqdn'] | default(hostvars[host]['ansible_fqdn']) }}:{{ mesos_zk_port }}{% if not loop.last %},{% endif %}{% endfor %}"
mesos_leader_port: 5050
mesos_follower_port: 5051

marathon_port: 5080

# TODO: use role=control ?
zookeeper_server_group: 'zookeeper'
mesos_leader_server_group: "mesos-leader"
mesos_mixed_server_group: "mesos-mixed"

mesos_leader_hostname_default: "
  {%- set mesos_leaders = groups[mesos_leader_server_group] + groups[mesos_mixed_server_group] -%}
  {{- hostvars[mesos_leaders[0]]['fqdn'] | default(hostvars[mesos_leaders[0]]['ansible_fqdn']) -}}
"
mesos_leader_hostname: "{{ mesos_leader_hostname_override | default(mesos_leader_hostname_default|trim) }}"
marathon_hostname: "{{ marathon_hostname_override | default(mesos_leader_hostname) }}"

internal_mesos_url: "http://{{ mesos_leader_hostname }}:{{ mesos_leader_port }}"
internal_marathon_url: "http://{{ marathon_hostname }}:{{ marathon_port }}"

metrics_prometheus_http_port: 31080

infrastructure_ports_internal: "
  {%- set ports = [] -%}
  {%- if zookeeper_port is defined and zookeeper_port -%}
    {%- set ports = ports + [zookeeper_port] -%}
  {%- endif -%}
  {%- if mesos_zk_port is defined and mesos_zk_port -%}
    {%- set ports = ports + [mesos_zk_port] -%}
  {%- endif -%}
  {%- if mesos_leader_port is defined and mesos_leader_port -%}
    {%- set ports = ports + [mesos_leader_port] -%}
  {%- endif -%}
  {%- if mesos_follower_port is defined and mesos_follower_port -%}
    {%- set ports = ports + [mesos_follower_port] -%}
  {%- endif -%}
  {%- if marathon_port is defined and marathon_port -%}
    {%- set ports = ports + [marathon_port] -%}
  {%- endif -%}
  {%- if ssh_port is defined and ssh_port -%}
    {%- set ports = ports + [ssh_port] -%}
  {%- endif -%}
  {{ ports }}
"

infrastructure_ports_public: "
  {%- set ports = [] -%}
  {%- if ssh_port is defined and ssh_port -%}
    {%- set ports = ports + [ssh_port] -%}
  {%- endif -%}
  {{ ports }}
"

infrastructure_swarm_ports:
  - 2377
  - 7946
  - 4789
