firewall_internal_ports: "{%- set tmp_ports = data_factory_ports_internal +
            hostpital_database_ports_internal +
            infrastructure_ports_internal +
            reference_ports_internal +
            web_analytics_ports_internal -%}
{%- set ports = []  -%}
{%- for port in tmp_ports -%}
{%-   set ports = ports.append(port|string) -%}
{%- endfor -%}
{{- ports -}}
"

firewall_host_ips: "
{%- set ips = [] -%}
{%- for host in groups['firewall'] -%}
{%-   set ips = ips.append(hostvars[host]['ansible_default_ipv4']['address']) -%}
{%- endfor -%}
{{- ips -}}
"

firewall_public_ports: "{{
  data_factory_ports_public +
  hostpital_database_ports_public +
  infrastructure_ports_public +
  reference_ports_public +
  web_analytics_ports_public
}}"

firewall_container_exposed_ports: "
  {%- set ports = [] -%}
  {%- set ports = ports + [ '5432' ] -%}{#- airflow-database + data-catalog-database + dev-services-database + i2b2-capture-database + i2b2-mip-database + ldsm-database + meta-database + mipmap-database + portal-database + research-database + woken-database -#}
  {%- set ports = ports + [ '22' ] -%}{#- cbrain-bourreau + cbrain-data-provider + gitlab -#}
  {%- set ports = ports + [ '3306' ] -%}{#- cbrain-database -#}
  {%- set ports = ports + [ '3000' ] -%}{#- cbrain-portal -#}
  {%- set ports = ports + [ '5000' ] -%}{#- docker-registry + mesos-ui -#}
  {%- set ports = ports + [ '80' ] -%}{#- gitlab -#}
  {%- set ports = ports + [ '8080' ] -%}{#- portal-backend -#}
  {%- set ports = ports + [ '4089' ] -%}{#- portal-backend -#}
  {%- set ports = ports + [ '5555' ] -%}{#- postgresraw-ui -#}
  {%- set ports = ports + [ '9000' ] -%}{#- sonarqube -#}
  {%- if woken_validation_akka_port is defined -%}
  {%-   set ports = ports + [ woken_validation_akka_port ] -%}{#- woken-validation -#}
  {%- endif -%}
  {%- set ports = ports + [ '8087' ] -%}{#- woken -#}
  {%- if woken_akka_port is defined -%}
  {%-   set ports = ports + [ woken_akka_port ] -%}{#- woken -#}
  {%- endif -%}
{{- ports -}}"
