---

chronos_marathon_id: /algorithm-factory/chronos
chronos_marathon_host: '{{ ansible_fqdn }}'

chronos_http_port: 4400
chronos_libprocess_port: 4401
chronos_ip_address: "{{ private_ipv4 }}"
chronos_web_url: "http://{{ chronos_marathon_host }}:{{ chronos_http_port }}/"

chronos_docker_image_basename: mesosphere/chronos
chronos_docker_image: "{{ chronos_docker_image_basename }}:{{ chronos_version }}"
chronos_command: >-
  /chronos/bin/start.sh
  --zk_hosts {{ chronos_zk_hosts }}
  --master {{ chronos_zk_mesos_master }}
  --webui_url {{ chronos_web_url }}
  --hostname {{ chronos_marathon_host }}
  --failure_retry {{ chronos_failure_retry }}
  --disable_after_failures {{ chronos_disable_after_failures }}
  --cluster_name {{ chronos_cluster_name }}
  --zk_timeout 30000

chronos_version: "v3.0.2"

chronos_zk_port: 2181
chronos_zk_hosts: "
  {%- set zk_hosts = [] -%}
  {%- for host in groups['zookeeper'] -%}
    {%- set host_fqdn = hostvars[host]['fqdn'] | default(hostvars[host]['ansible_fqdn']) -%}
    {%- set zk_hosts = zk_hosts + [host_fqdn + ':' + chronos_zk_port] -%}
  {% endfor %}
  {{- zk_hosts | join(',') -}}
"
chronos_zk_mesos_master: 'zk://{{ chronos_zk_hosts }}/mesos'

chronos_failure_retry: 5000
chronos_disable_after_failures: 1
chronos_cluster_name: '{{ mesos_cluster }}'
chronos_cpus: 0.5
chronos_mem: 512.0
chronos_docker_parameters: []
chronos_jvm_opts: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
