---

- fail:
    msg: "Bad configuration for chronos_zk_hosts, found localhost"
  when: "'localhost' in chronos_zk_hosts"

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  vars:
    uri: "{{ internal_marathon_url }}"

- name: Delete old Chronos app using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ chronos_marathon_id }}"
    state: "absent"
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"

- name: Launch Chronos using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ chronos_marathon_id }}"
    state: "present"
    cmd: "{{ chronos_command }}"
    docker_image: "{{ chronos_docker_image }}"
    docker_force_pull_image: true
    docker_network: HOST
    docker_port_mappings: []
    docker_parameters: '{{ chronos_docker_parameters }}'
    container_volumes: []
    env:
      PORT0: "{{ chronos_http_port }}"
      PORT1: "{{ chronos_libprocess_port }}"
      LIBPROCESS_IP: "{{ chronos_ip_address }}"
      JVM_OPTS: "{{ chronos_jvm_opts }}"
    instances: 1
    cpus: '{{ chronos_cpus }}'
    mem: '{{ chronos_mem }}'
    portDefinitions:
      - port: "{{ chronos_http_port }}"
        protocol: 'tcp'
        name: 'http'
      - port: "{{ chronos_libprocess_port }}"
        protocol: 'tcp'
        name: 'libprocess'
    require_ports: true
    constraints: [["hostname", "CLUSTER", "{{ chronos_marathon_host | trim }}"]]
    dependencies: []
    executor: ""
    wait_timeout: 600
    health_checks:
      - protocol: "{% if marathon_version | version_compare('1.4', '>=') %}MESOS_HTTP{% else %}HTTP{% endif %}"
        portIndex: 0
        path: "/"
        gracePeriodSeconds: 300
        intervalSeconds: 60
        timeoutSeconds: 20
        maxConsecutiveFailures: 2
    upgrade_strategy:
      minimumHealthCapacity: 0
      maximumOverCapacity: 0
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
