---

- hosts: managed
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/algorithm-factory/endpoints.yml"
    - "{{ play_dir }}/vars/data-factory/endpoints.yml"
    - "{{ play_dir }}/vars/hospital-database/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/web-analytics/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/firewall.yml"

  roles:

    # setup firewall
    - role: firewall_setfacts
      vars:
        - ips: "{{ firewall_host_ips }}"
        - ports: "{{ firewall_internal_ports }}"
        - swarm_ports: "{{ infrastructure_swarm_ports }}"
      when: manage_firewall | default(true)
      tags: ['infra', 'infrastructure', 'runtimes', 'firewall']
    - role: firewall
      vars:
        firewall_state: started
        firewall_enabled_at_boot: true
        firewall_allowed_tcp_ports: "{{ firewall_public_ports }}"
        firewall_additional_rules: "{{ firewall_rules  }}" # fact generated in firewall_setfacts
        firewall_disable_firewalld: true
        firewall_disable_ufw: true
      when: manage_firewall | default(true)
      tags: ['infra', 'infrastructure', 'runtimes', 'firewall']

